version: '3'
services:
    web:
        build: .
        volumes:
            - .:/home/node/app
            - /home/node/app/node_modules
        expose:
            - 8080
        ports:
            - 8080:8080